export const projectData = [
  {
    id: 1,
    url_live: 'https://amromoorie.github.io/apple-varieties/',
    url_repo: 'https://github.com/amromoorie/apple-varieties',
    name: 'Apple Varieties',
    description:
      'fully responsive landing page up to XL screens made with Tailwind',
    features: null,
    technologies: ['React', 'Tailwind', 'Nodejs', 'Cheerio'],
    notes:
      'project was originally meant for experimenting with web scraping with puppeteer & cheerio but ended with a nice design work! based on a real article',
    isFeatured: true,
  },
  {
    id: 2,
    url_live: 'https://amromoorie.github.io/taskify-mantine/',
    url_repo: 'https://github.com/amromoorie/taskify-mantine',
    name: 'Taskify',
    description: 'a todo app to experiment with mantine styling lib',
    features: [
      'add, delete, mark complete, filter out completed & show total number of todos',
      'todos has titles with content',
      'data saved in browser local storage',
    ],
    imgs: '',
    technologies: ['TypeScript', 'React', 'Mantine', 'react-hook-form'],
    notes: '',
    isFeatured: true,
  },
  {
    id: 3,
    url_live: 'https://amromoorie.github.io/Fido/',
    url_repo: 'https://github.com/amromoorie/Fido',
    name: 'Fido',
    description:
      'fido is a collection of dogs images using the dog api; the aim for this project is to experiment with pagination & modern redux toolkitt',
    features: [
      'pagination to different pages; enables users to specify a limit per page',
    ],
    imgs: '',
    technologies: ['React', 'Redux', 'TailwindCSS'],
    notes: '',
    isFeatured: true,
  },
  {
    id: 4,
    url_live: '',
    url_repo:
      'https://github.com/amromoorie/average-world-temperature.VanillaJS',
    name: 'Historical Zonal annual Means',
    description:
      'simple project working with chartJS tool, transforming csv data (global weather info) into tabulating data which can be visualized',
    features: null,
    imgs: '',
    technologies: ['VanillaJS', 'ChartJS', 'Webpack'],
    notes: '',
    isFeatured: false,
  },
  {
    id: 5,
    url_live: '',
    url_repo: 'https://github.com/amromoorie/banking-system',
    name: 'Backend Banking System',
    description: 'simple banking app made with mongodb and nodeJS',
    features: null,
    imgs: '',
    technologies: null,
    notes: '',
    isFeatured: false,
  },
  {
    id: 6,
    url_live: '',
    url_repo: 'https://github.com/amromoorie/blog',
    name: 'Simple Blog With Sanity',
    description:
      'project orginally developed for exploring strapi as a content first class model',
    features: null,
    imgs: '',
    technologies: ['React', 'NextJS', 'Strapi', 'Groq', 'TailwindCSS'],
    notes: '',
    isFeatured: false,
  },
  {
    id: 7,
    url_live: '',
    url_repo: 'https://github.com/amromoorie/Article-Sentiment-Analysisg',
    name: 'Article Sentiment Analysis',
    description:
      'Evaluate News Article with Natural Language Processing. It shows sentiment and analysis based on the article submitted based on meaningcloud API',
    features: null,
    imgs: '',
    technologies: ['VanillaJS', 'nodeJS', 'Webpack'],
    notes: '',
    isFeatured: false,
  },
];
